version: '3'

services:
  dentai-app:
    container_name: dentai-app
    build:
      context: .
      dockerfile: prod.Dockerfile
      args:
        MONGO_URI:  ${MONGO_URI}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        USERNAME: ${USERNAME}
        PASSWORD: ${PASSWORD}
        
    restart: always
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true